apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: yootoob-mp3

resources:
  - ../../base
  - certificate.yml
  - redirect-middleware.yml
  - redirect-ingress.yml

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: yootoob-mp3
    path: patch-ingress.yml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: yootoob-mp3-api
    path: patch-api.yml

images:
  - name: ghcr.io/isolumi/yootoob-mp3-api
    newName: ghcr.io/isolumi/yootoob-mp3-api
    newTag: f0ef2bc5f6a2c5e8edea9ae273d398c6ce7cb646
  - name: ghcr.io/isolumi/yootoob-mp3-frontend
    newName: ghcr.io/isolumi/yootoob-mp3-frontend
    newTag: f0ef2bc5f6a2c5e8edea9ae273d398c6ce7cb646
