apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: yootoob-mp3

resources:
  - ../../base

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: yootoob-mp3
    path: patch-ingress.yml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: yootoob-mp3-api
    path: patch-api.yml

images:
  - name: ghcr.io/isolumi/yootoob-mp3-api
    newName: ghcr.io/isolumi/yootoob-mp3-api
    newTag: f59fcd547ad50f0f65d64568d1bad16a5072febf
  - name: ghcr.io/isolumi/yootoob-mp3-frontend
    newName: ghcr.io/isolumi/yootoob-mp3-frontend
    newTag: f59fcd547ad50f0f65d64568d1bad16a5072febf
