apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: youtube-mp3

resources:
  - ../../base

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: youtube-mp3
    path: patch-ingress.yaml

images:
  - name: ghcr.io/isolumi/youtube-mp3-api
    newName: ghcr.io/isolumi/youtube-mp3-api
    newTag: development
  - name: ghcr.io/isolumi/youtube-mp3-frontend
    newName: ghcr.io/isolumi/youtube-mp3-frontend
    newTag: development
